# Generated by Django 5.0.1 on 2024-01-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MedicalHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("vaccinated", "Vaccinated"),
                            ("allergy", "Allergy"),
                            ("surgery", "Surgery"),
                            ("none", "None"),
                            ("other", "Other"),
                        ],
                        max_length=100,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WeightRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight", models.DecimalField(decimal_places=2, max_digits=5)),
                ("date", models.DateField()),
                (
                    "goal_weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("U", "Unknown")],
                        default="U",
                        max_length=1,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "species",
                    models.CharField(
                        choices=[
                            ("dog", "Dog"),
                            ("cat", "Cat"),
                            ("bird", "Bird"),
                            ("other", "Other"),
                        ],
                        default="dog",
                        max_length=30,
                    ),
                ),
                ("spayed_neutered", models.BooleanField(default=False)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="pet_app/"),
                ),
                ("breed", models.CharField(max_length=50)),
                ("age", models.IntegerField()),
                (
                    "medical_history",
                    models.ManyToManyField(blank=True, to="pets.medicalhistory"),
                ),
            ],
        ),
    ]
