# Generated by Django 5.0.1 on 2024-01-23 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("medicalvisit", "0001_initial"),
        ("pets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="petmedicalvisit",
            name="pet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medical_visits",
                to="pets.pet",
            ),
        ),
    ]
