# Generated by Django 5.0.1 on 2024-01-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userprofile", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="petowner",
            name="image",
        ),
        migrations.RemoveField(
            model_name="vetstaff",
            name="image",
        ),
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="pet_app/"),
        ),
    ]
