# Generated by Django 5.0.1 on 2024-02-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userprofile", "0003_remove_user_image_petowner_image_vetstaff_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Zip Code"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="country",
            field=models.CharField(
                blank=True,
                choices=[
                    ("US", "United States"),
                    ("CA", "Canada"),
                    ("GB", "United Kingdom"),
                ],
                max_length=2,
                null=True,
                verbose_name="Country",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="state",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="State"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="zip_code",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="state"
            ),
        ),
    ]
