# Generated by Django 5.0.1 on 2024-02-20 03:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0004_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="pet",
        ),
    ]
